name: pages build and deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # index.html 포함된 디렉토리

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
